<?php


namespace Transave\ScolaCbt\Tests\Unit\Models;


use Faker\Factory;
use Transave\ScolaCbt\Models\Admin;
use Transave\ScolaCbt\Models\User;
use Transave\ScolaCbt\Tests\TestCase;

class AdminModelTest extends TestCase
{
    private $admin;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->admin = Admin::factory()->create();
    }

    /** @test */
    public function admin_model_can_be_initiated_through_factory()
    {
        $this->assertTrue($this->admin instanceof Admin);
    }

    /** @test */
    public function admin_model_belongs_to_user_model()
    {
        $faker = Factory::create();
        $admins = Admin::factory()
            ->count(3)
            ->for(User::factory()->state([
                'first_name' => $faker->word,
                'last_name' => $faker->word,
            ]))
            ->create();
        $admin = Admin::query()->inRandomOrder()->first();
        $this->assertEquals(count($admins), 3);
        $this->assertTrue($admin->user instanceof User);
    }
}