<?php

namespace Transave\ScolaCbt\Tests\Unit\Models;

use Transave\ScolaCbt\Http\Models\User;
use Transave\ScolaCbt\Tests\TestCase;

class UserModelTest extends TestCase
{
    private $user;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    /** @test */
    public function user_model_can_be_initiated_with_factory()
    {
        $this->assertTrue($this->user instanceof User);
    }
}
