<?php


namespace Transave\ScolaCbt\Tests\Unit\Models;


use Orchestra\Testbench\TestCase;

class UserModelTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_can_check_if_user_model_exists()
    {

    }
}