<?php


namespace Transave\ScolaCbt\Tests\Feature\Auth;


use Laravel\Sanctum\Sanctum;
use Transave\ScolaCbt\Http\Models\User;
use Transave\ScolaCbt\Tests\TestCase;

class LoginTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function can_login_user_successfully()
    {
        $user = User::factory()->create([
            'email' => 'sampledata@test.com',
            'password' => bcrypt('sample1234'),
        ]);

        $loginData = ['email' => 'sampledata@test.com', 'password' => 'sample1234'];
        Sanctum::actingAs($user);

        $this->json('POST', 'cbt/login', $loginData, ['Accept' => 'application/json'])
            ->assertStatus(200)
            ->assertJsonStructure([
                "success",
                "message",
                "data"
            ]);

        $this->assertAuthenticated();
    }
}